import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { openDb, runMigrations } from '@zarb/storage';
import { WORKBENCH_DIR, WORKBENCH_CONFIG_FILE } from '@zarb/config';

const DATA_SUBDIRS = [
  'sqlite',
  'runs',
  'artifacts',
  'diagnostics',
  'analysis',
  'code-tasks',
  'commits',
  'generated-tests',
  'agent-traces',
];

const DEFAULT_CONFIG_YAML = `# zarb config — generated by zarb init
storage:
  sqlitePath: .zarb/data/sqlite/zarb.db

report:
  port: 3000

workspace:
  targetProjectPath: ''

ai:
  apiKeyEnvVar: OPENAI_API_KEY

trace:
  provider: none
  endpoint: ''

logs:
  provider: none
  endpoint: ''

diagnostics:
  correlationKeys:
    responseHeaders: []
    responseBodyPaths: []
    logFields: []

# Logging configuration
# level: debug | info | warn | error (default: info)
# file: write logs to .zarb/logs/zarb.log (default: true)
log:
  level: debug
  file: true
`;

export interface InitResult {
  configPath: string;
  dataRoot: string;
  alreadyInitialized: boolean;
}

/**
 * InitService — creates the local workbench directory structure,
 * writes a default config, and runs database migrations.
 * Derived from packaging-design.md §4 and §5.
 */
export class InitService {
  constructor(private readonly migrationsDir: string) {}

  init(workDir: string = process.cwd()): InitResult {
    const workbenchDir = join(workDir, WORKBENCH_DIR);
    const configPath = join(workDir, WORKBENCH_CONFIG_FILE);
    const dataRoot = join(workbenchDir, 'data');
    const alreadyInitialized = existsSync(configPath);

    // Create directory structure
    mkdirSync(workbenchDir, { recursive: true });
    for (const sub of DATA_SUBDIRS) {
      mkdirSync(join(dataRoot, sub), { recursive: true });
    }

    // Write default config only if not already present
    if (!alreadyInitialized) {
      writeFileSync(configPath, DEFAULT_CONFIG_YAML, 'utf8');
    }

    // Run migrations
    const dbPath = resolve(workDir, `${WORKBENCH_DIR}/data/sqlite/zarb.db`);
    mkdirSync(dirname(dbPath), { recursive: true });
    const db = openDb(dbPath);
    runMigrations(db, this.migrationsDir);
    db.close();

    return { configPath, dataRoot, alreadyInitialized };
  }

  /** Returns true if the workbench directory and config already exist. */
  isInitialized(workDir: string = process.cwd()): boolean {
    return existsSync(join(workDir, WORKBENCH_CONFIG_FILE));
  }
}
